name: 'Deploy to Firebase Cloud Functions node 18+'
author: 'amonc <amonchowdhury8@gmail.com>'
description: 'A GitHub Action to deploy to Firebase Cloud Functions on Node 18+'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'black'
